apiVersion: v1
kind: Service
metadata:
  name: prefect-server
  namespace: cac-mlops
  annotations:
    service.beta.kubernetes.io/scw-loadbalancer-type: "LB-S"
spec:
  type: LoadBalancer
  selector:
    app: prefect-server
  ports:
  - port: 4200
    targetPort: 4200
