apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow
  namespace: cac-mlops
  labels:
    app: mlflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow
  template:
    metadata:
      labels:
        app: mlflow
    spec:
      containers:
      - name: mlflow
        image: ghcr.io/jakatt/cac-mlops-mlflow:latest
        imagePullPolicy: Always
        command:
        - mlflow
        - server
        - --backend-store-uri=sqlite:////tmp/mlflow.db
        - --default-artifact-root=s3://cac-mlops-data/mlflow-k8s/
        - --host=0.0.0.0
        - --port=5000
        ports:
        - containerPort: 5000
        env:
        - name: MLFLOW_S3_ENDPOINT_URL
          value: "https://s3.fr-par.scw.cloud"
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: s3-creds
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: s3-creds
              key: AWS_SECRET_ACCESS_KEY
        volumeMounts:
        - name: mlflow-db
          mountPath: /tmp
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: "1"
            memory: 1Gi
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 15
          periodSeconds: 10

      volumes:
      - name: mlflow-db
        emptyDir: {}
